# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('value', models.CharField(max_length=500, verbose_name='Valeur')),
                ('value_type', models.CharField(choices=[('s', 'string'), ('i', 'integer'), ('f', 'float'), ('b', 'boolean')], max_length=1, verbose_name='Type')),
            ],
            options={
                'permissions': (('list_setting', 'Lister les paramètres généraux'), ('retrieve_setting', 'Afficher un paramètre général')),
            },
        ),
    ]
