# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 13:38
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Gestion manuelle du prix')),
                ('manual_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prix manuel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('unit', models.CharField(blank=True, choices=[('CL', 'cl'), ('G', 'g')], max_length=255, null=True, verbose_name='Unité')),
                ('correcting_factor', models.DecimalField(decimal_places=4, default=1, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Facteur correcteur de ventes')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Ne doit contenir que des lettres\n                                minuscules, sans espace ni caractère\n                                spécial.', regex='^[a-z]+$')], verbose_name='Code')),
                ('description', models.TextField(verbose_name='Description')),
                ('color', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Doit être dans le format #F4FA58', regex='^#[A-Za-z0-9]{6}')], verbose_name='Couleur')),
            ],
            options={
                'permissions': (('list_shop', 'Lister les magasins'), ('retrieve_shop', "Afficher les détails d'un magasin"), ('list_product', 'Lister les produits'), ('retrieve_product', "Afficher les détails d'un produit"), ('change_price_product', "Changer le prix d'un produit"), ('change_stock_product', "Régulariser le stock d'un produit")),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops_product_shop', to='shops.Shop'),
        ),
    ]
