# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfert',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_transfert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfert',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_transfert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedevent',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedevent',
            name='registered',
            field=models.ManyToManyField(blank=True, related_name='registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Product'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.Sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='sale',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='finances.SaleProduct', to='shops.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='recharging',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_recharging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recharging',
            name='payment_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.PaymentSolution'),
        ),
        migrations.AddField(
            model_name='recharging',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_recharging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsolution',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsolution',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionnalmovement',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_exceptionnal_movement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exceptionnalmovement',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_exceptionnal_movement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_bank_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cheque',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_bank_account', to='finances.BankAccount'),
        ),
    ]
