# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 08:14
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_category', models.CharField(default='ACTOR', max_length=20)),
                ('type', models.CharField(choices=[('DEBUG', 'debug'), ('SUCCESS', 'success'), ('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error')], default='INFO', max_length=10)),
                ('actor_id', models.PositiveIntegerField()),
                ('action_medium_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('displayed_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('read_datetime', models.DateTimeField(blank=True, null=True)),
                ('action_medium_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_action_medium', to='contenttypes.ContentType')),
                ('actor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor', to='contenttypes.ContentType')),
            ],
            options={
                'default_permissions': ('list',),
            },
        ),
        migrations.CreateModel(
            name='NotificationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('verbose_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_call_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'default_permissions': ('list', 'change'),
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('notificationgroup', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'default_permissions': ('list', 'add', 'change'),
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_template', models.TextField(blank=True, default='Une notification.', null=True, verbose_name='Template XML')),
                ('target_users', models.CharField(choices=[('ACTOR', "Acteur de l'action"), ('RECIPIENT', "Utilisateur cible de l'action"), ('TARGET_GROUPS', "Un ou plusieurs groupes d'utilisateurs")], default='ACTOR', max_length=20, verbose_name='Utilisateur destinataire de la notification')),
                ('type', models.CharField(choices=[('DEBUG', 'debug'), ('SUCCESS', 'success'), ('INFO', 'info'), ('WARNING', 'warning'), ('ERROR', 'error')], default='INFO', max_length=10, verbose_name='Type')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('last_call_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_activated', models.BooleanField(default=False, verbose_name='Template activé')),
                ('notification_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationClass', verbose_name='Action déclenchant la notification')),
                ('shop_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', verbose_name='Magasin concerné par la notification')),
                ('target_groups', models.ManyToManyField(blank=True, to='notifications.NotificationGroup', verbose_name="Groupe d'utilisateurs destinataire de la notification")),
            ],
            options={
                'default_permissions': ('list', 'add', 'change', 'deactivate'),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='group_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationGroup'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationClass'),
        ),
        migrations.AddField(
            model_name='notification',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_target', to='contenttypes.ContentType'),
        ),
    ]
